"use client";
import type { DashboardViewModel,Day } from "@/features/dashboard/model";
import { formatCurrency,formatDate,formatTime } from "@/features/dashboard/format";
import { groceryList } from "@/features/dashboard/selectors";
import { BudgetEditor } from "./budget-editor";
import { GroceryExport } from "./grocery-export";
import { Button } from "@/components/ui/button";
import { Table } from "@/components/ui/table";

const Pantry=({meal}:{meal:Day["meals"][number]})=>{const owned=meal.ingredients.filter(item=>item.inPantry),missing=meal.ingredients.filter(item=>!item.inPantry);return <div className="pantry-detail"><span className="tag">{owned.length} confirmed</span> <span className="tag orange">{missing.length} missing</span><div className="meta"><strong>At home:</strong> {owned.map(item=>item.name).join(", ")||"None confirmed"}<br/><strong>Needed:</strong> {missing.map(item=>`${item.name} (${item.pantryState})`).join(", ")||"Nothing missing"}<br/>Assumed/unknown items are not treated as owned.</div></div>};

export function RecommendationsPanel({day,model,budget,onBudget}:{day:Day;model:DashboardViewModel;budget:DashboardViewModel["budget"];onBudget:(a:number,c:DashboardViewModel["budget"]["cadence"])=>void}){
  const grocery=groceryList(day);
  const mealTime=(time:string)=>formatTime(day.date,time,model.locale,model.timeZone);
  return <section className="surface recommendations" aria-labelledby="meal-heading"><div className="section-head"><div><span className="eyebrow">Your next fuel</span><h2 id="meal-heading">Meals for {formatDate(day.date,model.locale,{weekday:"long",month:"long",day:"numeric"},model.timeZone)}</h2><p className="muted">Practical suggestions shaped by your demo plan, pantry and budget.</p></div><BudgetEditor amount={budget.amount} cadence={budget.cadence} onSave={onBudget} formatted={formatCurrency(budget.amount,model.locale,model.currency)}/></div>{day.meals.length===0?<div><p className="muted">No meals are available for this day. Plan a meal when you’re ready.</p><Button>Plan a meal</Button></div>:<><div className="table-wrap"><Table><thead><tr><th>Meal</th><th>Contribution</th><th>Cost</th><th>Pantry & groceries</th><th>Action</th></tr></thead><tbody>{day.meals.map(meal=><tr key={meal.id}><td><span className="meal-name">{meal.name}</span><br/><span className="meta">{meal.occasion} · {mealTime(meal.time)}</span><br/><span className="tag">{meal.status}</span></td><td>{meal.calories} kcal<br/><span className="meta">P {meal.protein}g · C {meal.carbs}g · F {meal.fat}g</span></td><td>{formatCurrency(meal.cost,model.locale,model.currency)}<br/><span className="meta">Estimated</span></td><td><Pantry meal={meal}/></td><td><Button disabled={Boolean(meal.allergyConflict)}>View meal</Button>{meal.allergyConflict&&<p className="error">Blocked: {meal.allergyConflict}</p>}</td></tr>)}</tbody></Table></div><div className="cards-mobile">{day.meals.map(meal=><article className="meal-card" key={meal.id}><span className="tag">{meal.status}</span><h3>{meal.name}</h3><p className="muted">{meal.occasion} · {mealTime(meal.time)}</p><div className="meal-detail"><span>Calories</span><strong>{meal.calories} kcal</strong><span>Protein</span><strong>{meal.protein} g</strong><span>Carbohydrates</span><strong>{meal.carbs} g</strong><span>Fat</span><strong>{meal.fat} g</strong><span>Estimated cost</span><strong>{formatCurrency(meal.cost,model.locale,model.currency)}</strong></div><Pantry meal={meal}/><br/><Button disabled={Boolean(meal.allergyConflict)}>View meal</Button>{meal.allergyConflict&&<p className="error">Blocked: {meal.allergyConflict}</p>}</article>)}</div><details className="grocery-preview"><summary>View grocery list ({grocery.length})</summary><ul>{grocery.map(item=><li key={item.name}>{item.name} · {item.quantity??"Quantity unavailable"} {item.unit??""} · for {item.meals.join(", ")}</li>)}</ul><p className="disclosure">Assumed and unknown pantry items remain qualified. Demo changes do not sync inventory.</p></details><div className="section-head export-actions"><GroceryExport items={grocery} locale={model.locale} currency={model.currency}/></div></>}</section>;
}
