import {describe,expect,it} from "vitest";import {fixtureDashboardProvider} from "@/features/dashboard/fixture-dashboard-provider";
describe("dashboard model",()=>{it("returns isolated deterministic fixture state",async()=>{const a=await fixtureDashboardProvider.getDashboard(),b=await fixtureDashboardProvider.getDashboard();a.budget.amount=1;a.contextsByDate[a.selectedDate][0].label="changed";a.reference.progressCards[0].percent="0%";a.reference.history.entries[0].recipe="changed";expect(b.budget.amount).toBe(18);expect(b.contextsByDate[b.selectedDate][0].label).not.toBe("changed");expect(b.reference.progressCards[0].percent).toBe("53%");expect(b.reference.history.entries[0].recipe).toBe("Garden egg toast");expect(a.days.every(d=>d.activity?.metrics.every(m=>m.value!==undefined)||d.activity?.access==="unavailable")).toBe(true);expect(Object.values(a.sectionStates).every(status=>status==="ready")).toBe(true);expect(b.sectionStates.history).toBe("ready");expect(b.reference.summary.bars).toHaveLength(7);expect(b.reference.activityCards).toHaveLength(6)});
it("exposes the exact bounded deterministic history fixture",async()=>{const {history}= (await fixtureDashboardProvider.getDashboard()).reference;expect(history.selectedDate).toBe("2026-07-13");expect(history.availableDateRange).toEqual(["2026-06-28","2026-07-25"]);expect(history.entries).toEqual([
{id:"history-2026-07-12-1",date:"2026-07-12",mealName:"Recovery breakfast",recipe:"Garden egg toast",workoutCalories:-320,recipeCalories:420,price:4.7},
{id:"history-2026-07-13-1",date:"2026-07-13",mealName:"Post-workout lunch",recipe:"Herby chickpea bowl",workoutCalories:-450,recipeCalories:420,price:6.8},
{id:"history-2026-07-13-2",date:"2026-07-13",mealName:"Afternoon recovery",recipe:"Cocoa banana bites",workoutCalories:-210,recipeCalories:420,price:2.6},
{id:"history-2026-07-14-1",date:"2026-07-14",mealName:"Morning meal",recipe:"Apple overnight oats",workoutCalories:-280,recipeCalories:420,price:3.9},
{id:"history-2026-07-15-1",date:"2026-07-15",mealName:"Midday refuel",recipe:"Roasted veggie wrap",workoutCalories:-390,recipeCalories:420,price:5.7}
]);expect(new Set(history.entries.map(entry=>entry.id)).size).toBe(history.entries.length);expect(history.entries.every(entry=>/^\d{4}-\d{2}-\d{2}$/.test(entry.date)&&Number.isInteger(entry.workoutCalories)&&entry.workoutCalories<0&&Number.isInteger(entry.recipeCalories)&&entry.recipeCalories>0&&entry.price>=0)).toBe(true);expect(history.entries.some(entry=>entry.date==="2026-07-16")).toBe(false)});});
