import { fireEvent,render,screen } from "@testing-library/react";
import { describe,expect,it,vi } from "vitest";
import { RecommendationsPanel } from "@/components/dashboard/recommendations-panel";
import { buildGroceryExportText } from "@/components/dashboard/grocery-export";
import { fixtureDashboardProvider,fixtureMealMatrix } from "@/features/dashboard/fixture-dashboard-provider";
import { groceryList,selectDay } from "@/features/dashboard/selectors";

describe("recommendations",()=>{
  it("renders full mobile meaning, localized time, pantry identities, and allergy blocking",async()=>{const model=await fixtureDashboardProvider.getDashboard(),day={...selectDay(model,"2026-07-15"),meals:[...fixtureMealMatrix,...selectDay(model,"2026-07-15").meals]};render(<RecommendationsPanel day={day} model={model} budget={model.budget} onBudget={vi.fn()}/>);for(const label of ["Breakfast","Snack","Pre-workout","Lunch","Afternoon snack","Dinner","recommended","planned","completed","skipped","unavailable"])expect(screen.getAllByText(new RegExp(label,"i")).length).toBeGreaterThan(0);expect(screen.getAllByText(/7:00 AM/).length).toBeGreaterThan(0);expect(screen.getAllByText("Carbohydrates").length).toBeGreaterThan(0);expect(screen.getAllByText("Fat").length).toBeGreaterThan(0);const pantryDetails=screen.getAllByText((_,element)=>Boolean(element?.classList.contains("meta")&&element.textContent?.includes("At home: Avocado")&&element.textContent?.includes("Needed: Chickpeas")));expect(pantryDetails.length).toBeGreaterThan(0);expect(screen.getAllByText(/Contains a listed peanut allergy/).length).toBeGreaterThan(0);expect(screen.getAllByRole("button",{name:"View meal"}).some(button=>(button as HTMLButtonElement).disabled)).toBe(true);fireEvent.click(screen.getByText(/View grocery list/));expect(screen.getAllByText(/Chickpeas/).length).toBeGreaterThan(0)});
  it("normalizes provider-neutral export content and disclaimer",async()=>{const model=await fixtureDashboardProvider.getDashboard(),items=groceryList(selectDay(model,model.selectedDate));const payload=buildGroceryExportText(items,model.locale,model.currency);expect(payload).toContain("Avilo Fit grocery list");expect(payload).toMatch(/Chickpeas — 1 can — Herby chickpea bowl/);expect(payload).toContain("$1.80");expect(payload).toContain("Costs are estimates. No retailer integration is connected.");expect(payload).not.toMatch(/Walmart|checkout|cart/i)});
  it("validates, cancels, and saves the local budget",async()=>{const model=await fixtureDashboardProvider.getDashboard(),onBudget=vi.fn();render(<RecommendationsPanel day={selectDay(model,model.selectedDate)} model={model} budget={model.budget} onBudget={onBudget}/>);fireEvent.click(screen.getByRole("button",{name:"Edit budget"}));const amount=screen.getByLabelText("Amount");fireEvent.change(amount,{target:{value:"-1"}});fireEvent.click(screen.getByRole("button",{name:"Save budget"}));expect(screen.getByText("Enter a non-negative amount.")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Cancel"}));expect(onBudget).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Edit budget"}));fireEvent.change(screen.getByLabelText("Amount"),{target:{value:"25"}});fireEvent.click(screen.getByRole("button",{name:"Save budget"}));expect(onBudget).toHaveBeenCalledWith(25,"day")});
});
